### ISSUE TITLE
Chef Server 12.0.1 - chef-server-ctl - ffi-yajl and yajl-ruby warning

### ISSUE THREAD

**Issue by tokenrain** [opscode/chef-server#53]
Running Chef Server 12.0.1 on CentOS 6.6 x86_64.

All chef-server-ctl commands result in a "warning" about what seems to be
conflicting gem packages in the 11.12.2 client that the embedded server uses
for convergence.

Is this anything that I should worry about? Is this a know issue?

Many Thanks!

root@is1 /root 1826# chef-server-ctl status

the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not
be loaded in the same Ruby VM
falling back to ffi which might work (or might not, no promises)
ffi-yajl/json_gem is deprecated, these monkeypatches will be dropped shortly

run: bookshelf: (pid 20835) 56758s; run: log: (pid 20107) 56790s
run: nginx: (pid 22664) 56273s; run: log: (pid 20507) 56764s
run: oc_bifrost: (pid 20556) 56763s; run: log: (pid 19572) 56818s
run: oc_id: (pid 20633) 56763s; run: log: (pid 19622) 56807s
run: opscode-erchef: (pid 20947) 56756s; run: log: (pid 20329) 56783s
run: opscode-expander: (pid 20734) 56759s; run: log: (pid 19846) 56798s
run: opscode-expander-reindexer: (pid 20784) 56758s; run: log: (pid 20020)
56795s
run: opscode-solr4: (pid 20662) 56761s; run: log: (pid 19775) 56801s
run: postgresql: (pid 20543) 56763s; run: log: (pid 19148) 56835s
run: rabbitmq: (pid 18086) 56848s; run: log: (pid 18099) 56848s
run: redis_lb: (pid 23622) 56000s; run: log: (pid 20473) 56770s

**Comment by mmzyk** [comment]
@tokenrain I don't believe you need to worry about this, although it isn't something I'd seen before, so thanks for the report.

**Comment by stevendanna** [comment]
Fix and discussion here: https://github.com/opscode/opscode-omnibus/pull/649

**Comment by dgarstang** [comment]
I believe I need to worry about this. See @2761. The message is displayed AND chef server does not appear to start.

**Comment by troyready** [comment]
@dgarstang the warning message hasn't prevented me from starting chef-server 12.0.1 on Ubuntu 14. You may be experiencing a separate problem, in which case I'd recommend opening a separate github issue.

**Comment by tylercloke** [comment]
This warning was fixed by this branch https://github.com/opscode/opscode-omnibus/pull/667 and will be shipped in next server release. Closing.

**Comment by darkn3rd** [comment]
I'm still seeing this on Chef Server 12.3 running on Cent OS 7.
